import { useState } from "react";
import type { InsightsResponse } from "../lib/types";
import { categoryLabel, formatKg } from "../lib/format";

interface Props {
  insights: InsightsResponse;
}

/**
 * Redesigned InsightsPanel component.
 * Includes interactive commitments checklist allowing users to simulate carbon savings.
 * Keeps standard list and text nodes for vitest compatibility.
 */
export function InsightsPanel({ insights }: Props) {
  const [committed, setCommitted] = useState<Record<number, boolean>>({});

  const sourceLabel = insights.source === "gemini" ? "AI-personalized" : "Smart rules";

  const toggleCommit = (index: number) => {
    setCommitted((prev) => ({
      ...prev,
      [index]: !prev[index],
    }));
  };

  const totalSimulatedSavings = insights.recommendations.reduce((sum, rec, index) => {
    return sum + (committed[index] ? rec.estimated_annual_savings_kg : 0);
  }, 0);

  return (
    <section className="card" aria-labelledby="insights-heading">
      <h2 id="insights-heading">
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" style={{ color: "var(--primary)" }} xmlns="http://www.w3.org/2000/svg">
          <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
        </svg>
        Personalized insights{" "}
        <span className="badge" title={`Generated by: ${sourceLabel}`}>
          {sourceLabel}
        </span>
      </h2>

      <p style={{ fontSize: "1.05rem", color: "#e5e7eb", marginBottom: "1.5rem" }}>
        {insights.summary}
      </p>

      {/* Simulated Savings Banner */}
      {totalSimulatedSavings > 0 && (
        <div className="simulation-banner" aria-live="polite">
          <div className="simulation-stats">
            <span className="title">Interactive simulation</span>
            <span className="description">Projected annual reduction from your commitments:</span>
          </div>
          <div className="simulation-value">
            -{formatKg(totalSimulatedSavings)} CO₂e / year
          </div>
        </div>
      )}

      <h3 style={{ fontFamily: "var(--font-display)", borderBottom: "1px solid var(--border)", paddingBottom: "0.5rem", marginBottom: "1rem" }}>
        Recommended actions
      </h3>
      <ul className="plain-list">
        {insights.recommendations.map((rec, i) => (
          <li className={`recommendation ${committed[i] ? "committed" : ""}`} key={`${rec.category}-${i}`}>
            <div className="recommendation-content">
              <strong>{categoryLabel(rec.category)}:</strong> {rec.action}
              <div className="saving">
                Potential saving: {formatKg(rec.estimated_annual_savings_kg)} CO₂e / year
              </div>
            </div>
            <div className="commit-checkbox-wrapper">
              <input
                type="checkbox"
                className="commit-checkbox"
                id={`commit-${i}`}
                checked={!!committed[i]}
                onChange={() => toggleCommit(i)}
                title="Commit to this action"
                aria-label={`Commit to action: ${rec.action}`}
              />
            </div>
          </li>
        ))}
      </ul>
    </section>
  );
}
