import { useState, useEffect } from "react";
import type { InsightsResponse } from "../lib/types";
import { categoryLabel, formatKg } from "../lib/format";

/** Props for the {@link InsightsPanel} component. */
interface Props {
  /** The AI-generated or rule-based insights response. */
  insights: InsightsResponse;
}

/**
 * Personalized insights panel with interactive commitment checkboxes.
 *
 * Users can toggle recommendations to simulate projected annual CO₂e
 * and financial savings. Includes an "Eco-Pledge" card for sharing.
 */
export function InsightsPanel({ insights }: Props) {
  const [committed, setCommitted] = useState<Record<number, boolean>>({});
  const [isGenerating, setIsGenerating] = useState(true);

  // Artificial generation delay for "Wow" factor
  useEffect(() => {
    setIsGenerating(true);
    const timer = setTimeout(() => setIsGenerating(false), 1500);
    return () => clearTimeout(timer);
  }, [insights]);

  const sourceLabel = insights.source === "gemini" ? "AI-personalized" : "Smart rules";

  const toggleCommit = (index: number) => {
    setCommitted((prev) => ({
      ...prev,
      [index]: !prev[index],
    }));
  };

  const getFinancialMultiplier = (category: string) => {
    switch (category) {
      case "transport":
        return 0.5;
      case "home":
        return 0.15;
      case "consumption":
        return 0.2;
      case "diet":
        return 0.3;
      default:
        return 0.25;
    }
  };

  const totalSimulatedSavings = insights.recommendations.reduce((sum, rec, index) => {
    return sum + (committed[index] ? rec.estimated_annual_savings_kg : 0);
  }, 0);

  const totalFinancialSavings = insights.recommendations.reduce((sum, rec, index) => {
    return (
      sum +
      (committed[index]
        ? rec.estimated_annual_savings_kg * getFinancialMultiplier(rec.category)
        : 0)
    );
  }, 0);

  if (isGenerating) {
    return (
      <section className="card insights-loading-wrapper">
        <div className="scanning-icon">
          <svg
            width="48"
            height="48"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
          </svg>
        </div>
        <h3>AI is analyzing your footprint...</h3>
        <p>Generating personalized reduction strategies.</p>
      </section>
    );
  }

  return (
    <section className="card" aria-labelledby="insights-heading">
      <h2 id="insights-heading">
        <svg
          width="24"
          height="24"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2"
          strokeLinecap="round"
          strokeLinejoin="round"
          className="insights-card-title-icon"
          xmlns="http://www.w3.org/2000/svg"
        >
          <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
        </svg>
        Personalized insights{" "}
        <span className="badge" title={`Generated by: ${sourceLabel}`}>
          {sourceLabel}
        </span>
      </h2>

      <p className="insights-intro-text">{insights.summary}</p>

      {/* Simulated Savings Banner */}
      {totalSimulatedSavings > 0 && (
        <div className="simulation-banner" aria-live="polite">
          <div className="simulation-stats">
            <span className="title">Interactive simulation</span>
            <span className="description">Projected annual reduction from your commitments:</span>
          </div>
          <div className="simulation-value">
            -{formatKg(totalSimulatedSavings)} CO₂e / yr
            <div className="insights-financial-savings-total">
              Est. savings: ~${totalFinancialSavings.toFixed(0)}/yr
            </div>
          </div>
        </div>
      )}

      <h3 className="insights-recommendations-header">Recommended actions</h3>
      <ul className="plain-list">
        {insights.recommendations.map((rec, i) => {
          const financialSaving =
            rec.estimated_annual_savings_kg * getFinancialMultiplier(rec.category);
          return (
            <li
              className={`recommendation ${committed[i] ? "committed" : ""}`}
              key={`${rec.category}-${i}`}
              style={{
                animationDelay: `${i * 0.15}s`,
              }}
            >
              <div className="recommendation-content">
                <strong>{categoryLabel(rec.category)}:</strong> {rec.action}
                <div className="saving">
                  Potential saving: {formatKg(rec.estimated_annual_savings_kg)} CO₂e / year
                  <span className="insights-financial-savings">
                    (~${financialSaving.toFixed(0)})
                  </span>
                </div>
              </div>
              <div className="commit-checkbox-wrapper">
                <input
                  type="checkbox"
                  className="commit-checkbox"
                  id={`commit-${i}`}
                  checked={!!committed[i]}
                  onChange={() => toggleCommit(i)}
                  title="Commit to this action"
                  aria-label={`Commit to action: ${rec.action}`}
                />
              </div>
            </li>
          );
        })}
      </ul>

      {/* Eco-Pledge Shareable Card */}
      {totalSimulatedSavings > 0 && (
        <div className="eco-pledge-card">
          <h4>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="var(--primary)" stroke="none">
              <path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm-1 17.93c-3.95-.49-7-3.85-7-7.93 0-.62.08-1.21.21-1.79L9 15v1c0 1.1.9 2 2 2v1.93zm6.9-2.54c-.26-.81-1-1.39-1.9-1.39h-1v-3c0-.55-.45-1-1-1H8v-2h2c.55 0 1-.45 1-1V7h2c1.1 0 2-.9 2-2v-.41c2.93 1.19 5 4.06 5 7.41 0 2.08-.8 3.97-2.1 5.39z" />
            </svg>
            My Eco-Pledge
          </h4>
          <p>
            I am committing to reduce my carbon footprint by{" "}
            <strong>{formatKg(totalSimulatedSavings)} CO₂e</strong> this year, and saving roughly{" "}
            <strong>${totalFinancialSavings.toFixed(0)}</strong> in the process!
          </p>
          <div className="eco-pledge-footer">
            <span>POWERED BY ECOMINDX</span>
            <button className="btn sm" type="button">
              Share Pledge
            </button>
          </div>
        </div>
      )}
    </section>
  );
}
