/**
 * Shared domain types used across the EcoMindX frontend application.
 *
 * These interfaces mirror the data contracts used by the Supabase database
 * and the Gemini-powered Edge Function, ensuring end-to-end type safety.
 *
 * @module types
 */

// ── Enumerations ────────────────────────────────────────────────────────────

/** Fuel type for a personal car. */
export type CarFuel = "petrol" | "diesel" | "hybrid" | "electric";

/** Self-reported dietary preference, ordered from highest to lowest emissions. */
export type DietType =
  | "heavy_meat"
  | "medium_meat"
  | "low_meat"
  | "pescatarian"
  | "vegetarian"
  | "vegan";

/** The four primary emission categories used throughout the application. */
export type EmissionCategory = "transport" | "home" | "diet" | "consumption";

// ── Carbon Input ────────────────────────────────────────────────────────────

/**
 * Structured lifestyle data collected from the 3-step calculator wizard.
 *
 * Each section maps to a specific emission category, allowing independent
 * calculation and targeted reduction advice.
 */
export interface CarbonInput {
  /** Weekly transport and aviation data. */
  transport: {
    /** Personal car distance driven per week, in kilometres. */
    car_km_per_week: number;
    /** Fuel type of the user's primary vehicle. */
    car_fuel: CarFuel;
    /** Weekly distance by public transit (bus, train, metro), in kilometres. */
    public_transit_km_per_week: number;
    /** Number of short-haul flights (< 3 hours) taken per year. */
    short_haul_flights_per_year: number;
    /** Number of long-haul flights (> 3 hours) taken per year. */
    long_haul_flights_per_year: number;
  };
  /** Monthly home energy consumption data. */
  home: {
    /** Monthly electricity usage in kilowatt-hours. */
    electricity_kwh_per_month: number;
    /** Monthly natural gas usage in kilowatt-hours. */
    natural_gas_kwh_per_month: number;
    /** Number of people sharing the home energy bill. */
    household_size: number;
  };
  /** The user's self-reported dietary preference. */
  diet: DietType;
  /** Monthly consumption and waste generation data. */
  consumption: {
    /** Monthly spend on consumer goods in USD. */
    goods_spend_usd_per_month: number;
    /** Weekly landfill-bound waste in kilograms. */
    waste_kg_per_week: number;
  };
}

// ── Footprint Result ────────────────────────────────────────────────────────

/**
 * Per-category annual emission breakdown in kilograms of CO₂-equivalent.
 *
 * Each key represents one of the four emission verticals. Values are
 * rounded to 2 decimal places by the calculation engine.
 */
export interface EmissionBreakdown {
  /** Annual transport emissions (car, transit, flights) in kg CO₂e. */
  transport: number;
  /** Annual home energy emissions (electricity, gas) in kg CO₂e. */
  home: number;
  /** Annual dietary emissions based on self-reported preference in kg CO₂e. */
  diet: number;
  /** Annual consumption & waste emissions in kg CO₂e. */
  consumption: number;
}

/** Contextual comparison of the user's footprint against reference benchmarks. */
export interface Comparison {
  /** The global average individual annual emissions in kg CO₂e (4,800 kg). */
  global_average_annual_kg: number;
  /** The sustainable Paris-aligned individual target in kg CO₂e (2,000 kg). */
  sustainable_target_annual_kg: number;
  /** Ratio of user's total emissions to the global average (1.0 = average). */
  ratio_to_global_average: number;
  /** Ratio of user's total emissions to the sustainable target (< 1.0 = on track). */
  ratio_to_sustainable_target: number;
}

/**
 * Complete annual carbon footprint assessment result.
 *
 * Produced by {@link calculateFootprint} and stored in the database as a
 * JSONB column alongside the original input.
 */
export interface FootprintResult {
  /** Per-category emission breakdown in kg CO₂e. */
  breakdown_kg: EmissionBreakdown;
  /** Total annual emissions across all categories in kg CO₂e. */
  total_annual_kg: number;
  /** Total annual emissions in metric tonnes (total_annual_kg / 1000). */
  total_annual_tonnes: number;
  /** Comparison ratios against global and sustainable benchmarks. */
  comparison: Comparison;
}

// ── AI Insights ─────────────────────────────────────────────────────────────

/**
 * A single actionable recommendation for reducing emissions in a specific
 * category, generated by the Gemini AI or the deterministic rules engine.
 */
export interface Recommendation {
  /** The emission category this recommendation targets. */
  category: string;
  /** A concise, actionable description of the recommended behaviour change. */
  action: string;
  /** Projected annual emission reduction from following this advice, in kg CO₂e. */
  estimated_annual_savings_kg: number;
}

/**
 * Complete AI insights response containing a personalised summary and
 * prioritised reduction recommendations.
 */
export interface InsightsResponse {
  /** A human-friendly summary assessing the user's footprint against targets. */
  summary: string;
  /** Up to 4 prioritised recommendations, ordered by potential impact. */
  recommendations: Recommendation[];
  /** Whether the response came from Google Gemini or the local rules engine. */
  source: "gemini" | "rules";
}

// ── Persistence ─────────────────────────────────────────────────────────────

/**
 * A saved footprint snapshot stored in Supabase, linking input data,
 * calculated results, and optional user ownership.
 */
export interface Entry {
  /** Unique database identifier (UUID). */
  id: string;
  /** ISO 8601 timestamp of when the entry was created. */
  created_at: string;
  /** Anonymous device identifier for pre-authentication tracking. */
  device_id: string;
  /** The original lifestyle input data used for this calculation. */
  input: CarbonInput;
  /** The calculated carbon footprint result. */
  result: FootprintResult;
  /** Authenticated user ID, or `undefined` for anonymous entries. */
  user_id?: string;
}

// ── Community ───────────────────────────────────────────────────────────────

/** A row from the `leaderboard` database view, ranking users by emissions. */
export interface LeaderboardEntry {
  /** The user's unique ID. */
  user_id: string;
  /** The user's display name (derived from email prefix or profile). */
  display_name: string;
  /** The user's latest annual emissions in tonnes CO₂e (lower is better). */
  score: number;
}

/** A crowd-sourced eco-tip shared through the Community Hub. */
export interface CommunityTip {
  /** Unique database identifier (UUID). */
  id: string;
  /** ISO 8601 timestamp of when the tip was shared. */
  created_at: string;
  /** The emission category this tip relates to. */
  category: string;
  /** Short, descriptive title for the tip. */
  title: string;
  /** Detailed explanation of the tip and its environmental benefit. */
  description: string;
  /** Display name of the tip's author. */
  author_name: string;
  /** The authenticated user who shared this tip, if applicable. */
  user_id?: string;
}

// ── Factories ───────────────────────────────────────────────────────────────

/**
 * Create a fresh, all-zero {@link CarbonInput} with sensible defaults.
 *
 * Used as the initial state for the calculator wizard form. Diet defaults
 * to `"medium_meat"` and car fuel to `"petrol"` as the most common choices.
 *
 * @returns A new `CarbonInput` with all numeric fields set to zero.
 */
export const emptyInput = (): CarbonInput => ({
  transport: {
    car_km_per_week: 0,
    car_fuel: "petrol",
    public_transit_km_per_week: 0,
    short_haul_flights_per_year: 0,
    long_haul_flights_per_year: 0,
  },
  home: {
    electricity_kwh_per_month: 0,
    natural_gas_kwh_per_month: 0,
    household_size: 1,
  },
  diet: "medium_meat",
  consumption: {
    goods_spend_usd_per_month: 0,
    waste_kg_per_week: 0,
  },
});
